pipeline {
    agent any
    stages {
        stage("run frontend") {
            steps { 
                echo 'executing yarn...'
                nodejs('Node-10.0') {
                    sh 'yarn install'
                }
            }
        }
    }
}
