pipeline {
    agent any
    stages {
        stage("Build") {
            steps { 
                echo 'executing npm...'
                nodejs('Node-10.0') {
                    sh 'npm install'
                }
            }
        }
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
        stage('Deliver') {
            steps {
                sh 'set -x'
                sh 'npm run build'
                sh 'set -x'
                sh 'npm start & sleep 1'
                sh 'set -x'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh 'kill $(cat .pidfile)'
            }     
        }
    }
}
