pipeline {
    agent any
    stages {
        stage("Build") {
            steps { 
                echo 'executing yarn...'
                nodejs('Node-10.0') {
                    sh 'yarn install'
                }
            }
        }
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
        stage('Deliver') {
            steps {
                sh 'yarn start'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh 'kill $(cat .pidfile)'
            }     
        }
    }
}
